@echo off
echo Starting Revolt Motors Voice Chatbot...
echo.
echo Starting backend server...
start "Backend Server" cmd /k "cd server && npm run dev"
echo.
echo Starting frontend...
start "Frontend" cmd /k "npm run dev"
echo.
echo Both services are starting...
echo Backend: http://localhost:3001
echo Frontend: http://localhost:5173
echo.
echo Press any key to exit this launcher...
pause >nul
